### ISSUE TITLE
Link to Project Not Available

### ISSUE THREAD

**Issue by its-aye-lisa** [Andergraw/supabase-auth-ui-plasmic#1]
When clicking to see the link in the repo, the project didn't open. 

Potential Solutions: Did you host the project somewhere and then add that link back into the configuration?

![image](https://github.com/Andergraw/supabase-auth-ui-plasmic/assets/65581330/ab62e7ea-60b9-4b85-9f8f-c1123d7c0ba9)

**Comment by Andergraw** [comment]
Since it's a project with custom code, you need to download and set the Github repo first to port 3000 in order to run the plasmic one.

**Comment by its-aye-lisa** [comment]
Ok, it might make sense to make that clear in the ReadMe

It currently states "I have also created a demo project in Plasmic"  with a link that takes you to the project, so the assumption would with what is written there, that you'd be able to go directly to the project. 

The original [Supabse Demo](https://github.com/plasmicapp/plasmic/tree/master/examples/supabase-demo) also has custom code components, but the link in the ReadMe to the Plasmic Project takes you to the Project and it is visible without doing the extra steps of downloading the code and configuring the project to localhost because they've hosted the project to `plasmic-supabase-demo-git-master-plasmic.vercel.app/plasmic-host ` so that when someone goes to the projec they custom code components are available. 

The plasmic documentation has the [recommendation](https://docs.plasmic.app/learn/multiple-environments/#recommendations) on how to manage the code components and app hosts.

**Comment by Andergraw** [comment]
First of all, I appreciate your effort in making this repo more complete :). I'm editing the readme to make your point more clear. 

Nevertheless, if you have already played with the Plasmic ecosystem, their example is different, since the components they are using are Plasmic components being substituted with custom code (I am talking about the [Github project referenced here](https://github.com/plasmicapp/plasmic/tree/master/examples/supabase-auth-nextjs-pages-loader), not the Supabase one you are linking). This is an imported whole custom component that NEEDS to be app hosted in order to be available in the Plasmic Studio editor. It's a different scenario. 
Sorry, but deploying this example to Vercel is beyond the scope of the repo. Maybe in the future I update it.

On the other hand, as stated in the readme, this is not an example made to cover the whole process of starting with Plasmic, but goes directly into making this component work with Plasmic Auth integration.
